### ISSUE TITLE
Nutzersuche für Scio Support freischalten

### ISSUE THREAD

**Issue by lassnj** [BiP-org/moodle-local_displace#31]
Scio Support sollte Zugriff auf die Nutzersuche erhalten. Bitte die Einschränkung auf admin() auf eine Capability umschreiben.

**Comment by rschrenk** [comment]
Eventuell mit Capability `moodle/user:viewalldetails` arbeiten.

**Comment by rschrenk** [comment]
Capability wurde als `local/displace:admin_user_viewtable` umgesetzt.

- [x] Rolle `bip_support` angelegt
- [x] Capability zugeschalten
- [x] Rolle global zugeteilt an [Daniela Steiger](https://www.bildung.gv.at/user/profile.php?id=961885)
